# Celebal_Assignment_1

## Objective
Learn Python basics and perform data exploration and cleaning using Pandas.

## Step 1: Import Required Libraries

In [3]:
import pandas as pd

## Step 2: Load the Dataset

In [4]:
df = pd.read_csv("dresses.csv")

In [5]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,NaN,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

## Step 3: data exploration

In [6]:
df.head(12)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,NaN,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
5,21664936,Label Ritu Kumar,Candy Striped Pure Cotton Maxi Dress,0.0,0,5900.0,30.0,"""₹4,130.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Rel███ce ███uku█████████Ltd███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
6,21665324,Harpa,Sweetheart Neck Puff Sleeves Sheath Dress,2.3,4,1999.0,55.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,HAR███RET███ PV█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,"45-███ FI███ FL█████████C,O███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
7,21664854,aarke Ritu Kumar,Cotton A-Line Dress,4.0,6,2200.0,30.0,"""₹1,540.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",NaN,Rel███ce ███uku█████████Ltd███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
8,21664974,Label Ritu Kumar,Candy Striped Pure Cotton Wrap Dress,4.6,7,4500.0,30.0,"""₹3,150.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Rel███ce ███uku█████████Ltd███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
9,21664840,aarke Ritu Kumar,Floral Georgette A-Line Midi Dress,4.0,6,3500.0,30.0,"""₹2,450.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",NaN,Rel███ce ███uku█████████Ltd███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
10,21980370,Tokyo Talkies,Mini A-Line Dress,3.7,26,1599.0,79.0,"""₹335.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":5,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",NaN,3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
11,21616436,Curves by MISH,Plus Size Shoulder Straps Embellished Maxi Dress,0.0,0,3999.0,37.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",MIS███ESI███ LI██████,"[{""size"":""XL"",""value"":""40.0in"",""value_name"":""T...",NaN,GAL███O 4███ULA█████████IRE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [7]:
df.tail(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
90,22590644,YU by Pantaloons,Shoulder Straps Schiffli Cotton A-Line Dress,4.7,17,1399.0,54.0,"""₹643.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_P████████████,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...",NaN,Wes███ry ███din█████████e L███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
91,13375140,HOUSE OF KKARMA,Women Navy Blue Printed A-Line Dress,3.9,17,3499.0,65.0,"""₹1,224.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Mut███ar,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",NaN,"1ST███OOR███-80█████████88,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
92,13398280,Zastraa,Women Grey Solid Sheath Dress,4.3,45,3299.0,70.0,"""₹989.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",MON███ CR███ION█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",NaN,GAL███O. ███2ND█████████-64███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
93,12933978,Oxolloxo,Women Orange Solid Fit and Flare Dress,0.0,0,1899.0,64.0,"""₹669.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
94,13379612,THE SILHOUETTE STORE,Women Orange Solid Maxi Dress,2.0,3,1399.0,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,YOL███ESI███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,207███rak███ to█████████cou███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [8]:
df.shape

(100, 24)

In [9]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [10]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

## Step 4: Identify Missing Values

In [11]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,True,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
98,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False

In [12]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   8
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       37
seller_name               10
sizes                      0
videos                    90
seller_information        10
variations                61
best_offer                 0
more_offers                0
category                   0
dtype: int64

## Step 5: Handle Missing Values

In [13]:
df["discount"] = df["discount"].fillna(0)

In [14]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [15]:
df["seller_name"] = df["seller_name"].fillna("unknown")

In [16]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [17]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       37
seller_name                0
sizes                      0
videos                    90
seller_information        10
variations                61
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [18]:
df["what_customers_said"] = df["what_customers_said"].fillna("no reviews")

In [19]:
df["seller_information"] = df["seller_information"].fillna("no info")

In [20]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...",NaN,"604███TH ███OR,█████████ITA███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Kil███5/1███ 18█████████ 22███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",no reviews,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",NaN,243███244███ Pa█████████rat█████████████████████,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",no reviews,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...",NaN,"D-2███09,███CTO█████████ , █████████████████████1",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...",NaN,"C B███K, ███ FL█████████HEB███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4th███oor███he █████████ide███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",NaN,KHA███ NO███/13█████████8/2███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...",NaN,"615███hur███ate█████████,5 ███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [21]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        0
seller_name                0
sizes                      0
videos                    90
seller_information         0
variations                61
best_offer                 0
more_offers                0
category                   0
dtype: int64

## Step 6: Remove Unnecessary Columns

In [22]:
df=df.drop(columns=["videos","variations"])

In [23]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...","604███TH ███OR,█████████ITA███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Kil███5/1███ 18█████████ 22███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
3,21426632,Trendyol,Floral Printed Shoulder strap A-Line Mini Dress,3.9,35,3599.0,30.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":6,""2_stars"":2,""3_stars"":1,""4_stars"":...",no reviews,Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",243███244███ Pa█████████rat█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",no reviews,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...","D-2███09,███CTO█████████ , █████████████████████1","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...","C B███K, ███ FL█████████HEB███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
97,22596522,Vero Moda,Shoulder Straps Cut Out Smocked A-Line Midi Dress,4.3,12,3799.0,65.0,"""₹1,329.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",VER███ODA███TAI█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",4th███oor███he █████████ide███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",KHA███ NO███/13█████████8/2███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

## Step 7: Select Specific Columns

In [24]:
df2=df[["product_id","title","initial_price"]]

In [25]:
df2

    product_id           title  initial_price
0     21664722      Curvy Clan         2999.0
1     21426422        Trendyol         4399.0
2     21238004     COVER STORY         3490.0
3     21426632        Trendyol         3599.0
4     21673378          RACHNA         1299.0
..         ...             ...            ...
95    22630128     NUEVOSDAMAS         1999.0
96    22610562      NIGHTSPREE         2299.0
97    22596522       Vero Moda         3799.0
98    22619942           Styli         2799.0
99    13400194  Style Quotient         1299.0

[100 rows x 3 columns]

## Step 8: Filter Dataset

In [26]:
df3=df[df["initial_price"]<3000.0]

In [27]:
df3

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...","604███TH ███OR,█████████ITA███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",243███244███ Pa█████████rat█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
6,21665324,Harpa,Sweetheart Neck Puff Sleeves Sheath Dress,2.3,4,1999.0,55.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,HAR███RET███ PV█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","45-███ FI███ FL█████████C,O███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
7,21664854,aarke Ritu Kumar,Cotton A-Line Dress,4.0,6,2200.0,30.0,"""₹1,540.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
10,21980370,Tokyo Talkies,Mini A-Line Dress,3.7,26,1599.0,79.0,"""₹335.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,13379612,THE SILHOUETTE STORE,Women Orange Solid Maxi Dress,2.0,3,1399.0,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",no reviews,YOL███ESI███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",207███rak███ to█████████cou███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
95,22630128,NUEVOSDAMAS,Girls Polka Dot Printed Crepe Fit & Flare Dress,2.8,5,1999.0,70.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",no reviews,M/S███V M███C.,"[{""size"":""2-3Y"",""value"":""22.0in"",""value_name"":...","D-2███09,███CTO█████████ , █████████████████████1","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
96,22610562,NIGHTSPREE,Band Collar Floral Printed Maternity Fit & Fla...,0.0,0,2299.0,50.0,"""₹1,149.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,MAH███R E███RPR██████,"[{""size"":""M"",""value"":""48.0in"",""value_name"":""Fr...","C B███K, ███ FL█████████HEB███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
98,22619942,Styli,Burgundy Puff Sleeve Accordion Pleated Fit & F...,3.7,11,2799.0,51.0,"""₹1,371.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",PRE███RE ███AIL█████████PRI███████████████,"[{""size"":""S"",""value"":""33.1in"",""value_name"":""To...",KHA███ NO███/13█████████8/2███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
99,13400194,Style Quotient,Girls Navy Blue Striped Drop-Waist Dress,0.0,0,1299.0,73.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""2-3Y"",""value"":""9.0in"",""value_name"":""...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [28]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

## Step 9: Remove Duplicate Records

In [29]:
df=df.drop_duplicates(subset=["title"])

In [30]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Colourblocked A-Line dressV-ne...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...","604███TH ███OR,█████████ITA███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid solid maxi dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""embellished solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Kil███5/1███ 18█████████ 22███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black floral print a-line dr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",243███244███ Pa█████████rat█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
5,21664936,Label Ritu Kumar,Candy Striped Pure Cotton Maxi Dress,0.0,0,5900.0,30.0,"""₹4,130.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Multicoloured striped fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
6,21665324,Harpa,Sweetheart Neck Puff Sleeves Sheath Dress,2.3,4,1999.0,55.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid sheath dressSweetheart n...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,HAR███RET███ PV█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","45-███ FI███ FL█████████C,O███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
7,21664854,aarke Ritu Kumar,Cotton A-Line Dress,4.0,6,2200.0,30.0,"""₹1,540.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Green chevron print a-line d...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
10,21980370,Tokyo Talkies,Mini A-Line Dress,3.7,26,1599.0,79.0,"""₹335.00""",INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid A-line dressRound neckSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
11,21616436,Curves by MISH,Plus Size Shoulder Straps Embellished Maxi Dress,0.0,0,3999.0,37.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid maxi dressShoulder strap...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",MIS███ESI███ LI██████,"[{""size"":""XL"",""value"":""40.0in"",""value_name"":""T...",GAL███O 4███ULA█████████IRE███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
12,21988674,Sangria,Floral Printed Tiered A-Line Dress,0.0,0,2999.0,80.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue floral print a-line dre...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",D-2███Sec███ 06█████████uta███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
13,22004792,WoowZerz,Button Detailed Mini Blazer Dress,4.8,26,2495.0,50.0,"""₹1,247.00""",INR,http://assets.myntassets.com/assets/images/220...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid blazer dressLapel collar...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Man███ Fa███ona██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",B-8███2nd███oor█████████r I███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
14,21979790,Vishudh,Floral Printed A-Line Midi Dress,3.8,55,2049.0,77.0,"""₹471.00""",INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Turquoise blue floral print a-...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":3,""3_stars"":8,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Tight""}...",Fla███tar███mme██████,"[{""size"":""S"",""value"":""36.5in"",""value_name"":""Bu...","1st███oor███abi█████████02,███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
15,18962890,Athena,Fuchsia Solid Asymmetric Hem A-Line Maxi Dress,4.0,34,2499.0,64.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Fuchsia solid A-line dressShou...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
16,19027298,DressBerry,Girls Pink & Navy Blue Floral Printed Shirt Co...,3.8,40,1499.0,41.0,"""₹884.00""",INR,http://assets.myntassets.com/assets/images/190...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink and navy blue floral pr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":6,""4_stars"":...",no reviews,Vis███ St███,"[{""size"":""12-13Y"",""value"":""28.0in"",""value_name...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
18,18951626,Berrylush,Women Green Solid Twist & Knot Dress,4.0,60,1899.0,78.0,"""₹398.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Look ravishing when you wear t...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""33.5in"",""value_name"":""Fr...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
19,18816460,Ethnovog,Women Navy Blue Velvet A-Line Made To Measure ...,3.7,6,7828.0,52.0,"""₹3,757.00""",INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy blue solid a-line dressSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Net███enu███ech█████████Pvt██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o.1███ari█████████oun███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
20,18944812,DRAAX Fashions,Pink Chiffon Fit and Flare Dress,3.6,8,2399.0,0.0,"""₹2,399.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink self design self design...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Dra███Fas███ns █████████vat████████████,"[{""size"":""XXS"",""value"":""32.0in"",""value_name"":""...",D-1███ Se███r-7█████████B. ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
21,18977246,AURELIA,Blue Ethnic Motifs Maxi Dress,4.1,140,4299.0,59.0,"""₹1,750.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue ethnic motifs print max...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":13,""2_stars"":5,""3_stars"":12,""4_stars...","[{""percentage"":""77"",""value_name"":""Fit, Just Ri...",Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Vil███e B███a B█████████ata███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
22,18803110,Athena Girl,Yellow Floral Dress,3.5,6,2299.0,74.0,"""₹597.00""",INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Yellow floral print fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",no reviews,APE███PPA███S,"[{""size"":""10-11Y"",""value"":""2.25in"",""value_name...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
25,18956684,Forevermore,Mustard Yellow Chiffon Embroidred Ruffle Tiere...,4.2,5,1599.0,0.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Mustard yellow self design p...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",no reviews,Ami███nte███ise███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",10/███CHH███YA █████████ILL███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
26,18981160,Amydus,Blue & Orange Floral Wrap Dress,4.7,43,2799.0,0.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue and orange floral print...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BEG███01 ███EST██████,"[{""size"":""XXL"",""value"":""41.0in"",""value_name"":""...","357███has███, U█████████r, ███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
28,18207844,H&M,Women Blue Linen-blend Shirt Dress,3.0,7,1999.0,0.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/182...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Knee-length dress in soft jers...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""31.5in"",""value_name"":""B...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses
29,15736838,U&F,Black Solid Maxi Dress,3.8,1023,1999.0,66.0,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/157...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A casual fit with v-neckline, ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":140,""2_stars"":69,""3_stars"":124,""4_st...","[{""percentage"":""66"",""value_name"":""Fit, Just Ri...",SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","A-4███ect███7 N█████████ , █████████████████████1","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
31,15691054,QUIERO,Women Alluring Grey Polka Dots Trapeze Dress,3.4,7,2686.0,65.0,"""₹940.00""",INR,http://assets.myntassets.com/assets/images/156...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Get into fun mode every time y...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",no reviews,Per███nkl███esi██████,"[{""size"":""XS"",""value"":""9.25in"",""value_name"":""S...",B-1███1st███2nd█████████tor███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
33,13770986,all about you,Black Solid Midi Halter Neck Fit and Flare Dress,4.2,38,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid fit & flare dres...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses
34,17586858,RARE,Women Orange Georgette A-Line Midi Dress,3.4,23,1799.0,55.0,"""₹809.00""",INR,http://assets.myntassets.com/assets/images/175...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Orange geometric print a-lin...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",EPI███RAN███PVT██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",EPI███RAN███PVT█████████ FI███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
35,17692606,Style Quotient,Women Navy Blue Solid Cut-Out Detail Sheath Mi...,3.9,12,1899.0,53.0,"""₹892.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Navy blue solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses

In [31]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'seller_information', 'best_offer',
       'more_offers', 'category'],
      dtype='str')

## Step 10: Create Quantity Column

In [32]:
df["quantity"] = 2

In [33]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,quantity
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Colourblocked A-Line dressV-ne...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...","604███TH ███OR,█████████ITA███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,"""₹2,419.00""",INR,http://assets.myntassets.com/assets/images/214...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid solid maxi dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,"""₹2,094.00""",INR,http://assets.myntassets.com/assets/images/212...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""embellished solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Kil███5/1███ 18█████████ 22███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,"""₹628.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black floral print a-line dr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",243███244███ Pa█████████rat█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
5,21664936,Label Ritu Kumar,Candy Striped Pure Cotton Maxi Dress,0.0,0,5900.0,30.0,"""₹4,130.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Multicoloured striped fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
6,21665324,Harpa,Sweetheart Neck Puff Sleeves Sheath Dress,2.3,4,1999.0,55.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid sheath dressSweetheart n...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,HAR███RET███ PV█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","45-███ FI███ FL█████████C,O███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
7,21664854,aarke Ritu Kumar,Cotton A-Line Dress,4.0,6,2200.0,30.0,"""₹1,540.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Green chevron print a-line d...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
10,21980370,Tokyo Talkies,Mini A-Line Dress,3.7,26,1599.0,79.0,"""₹335.00""",INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid A-line dressRound neckSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
11,21616436,Curves by MISH,Plus Size Shoulder Straps Embellished Maxi Dress,0.0,0,3999.0,37.0,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid maxi dressShoulder strap...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",MIS███ESI███ LI██████,"[{""size"":""XL"",""value"":""40.0in"",""value_name"":""T...",GAL███O 4███ULA█████████IRE███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
12,21988674,Sangria,Floral Printed Tiered A-Line Dress,0.0,0,2999.0,80.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue floral print a-line dre...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",D-2███Sec███ 06█████████uta███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
13,22004792,WoowZerz,Button Detailed Mini Blazer Dress,4.8,26,2495.0,50.0,"""₹1,247.00""",INR,http://assets.myntassets.com/assets/images/220...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid blazer dressLapel collar...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Man███ Fa███ona██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",B-8███2nd███oor█████████r I███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
14,21979790,Vishudh,Floral Printed A-Line Midi Dress,3.8,55,2049.0,77.0,"""₹471.00""",INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Turquoise blue floral print a-...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":3,""3_stars"":8,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Tight""}...",Fla███tar███mme██████,"[{""size"":""S"",""value"":""36.5in"",""value_name"":""Bu...","1st███oor███abi█████████02,███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
15,18962890,Athena,Fuchsia Solid Asymmetric Hem A-Line Maxi Dress,4.0,34,2499.0,64.0,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Fuchsia solid A-line dressShou...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
16,19027298,DressBerry,Girls Pink & Navy Blue Floral Printed Shirt Co...,3.8,40,1499.0,41.0,"""₹884.00""",INR,http://assets.myntassets.com/assets/images/190...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink and navy blue floral pr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":6,""4_stars"":...",no reviews,Vis███ St███,"[{""size"":""12-13Y"",""value"":""28.0in"",""value_name...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
18,18951626,Berrylush,Women Green Solid Twist & Knot Dress,4.0,60,1899.0,78.0,"""₹398.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Look ravishing when you wear t...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""33.5in"",""value_name"":""Fr...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
19,18816460,Ethnovog,Women Navy Blue Velvet A-Line Made To Measure ...,3.7,6,7828.0,52.0,"""₹3,757.00""",INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy blue solid a-line dressSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Net███enu███ech█████████Pvt██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o.1███ari█████████oun███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
20,18944812,DRAAX Fashions,Pink Chiffon Fit and Flare Dress,3.6,8,2399.0,0.0,"""₹2,399.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink self design self design...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Dra███Fas███ns █████████vat████████████,"[{""size"":""XXS"",""value"":""32.0in"",""value_name"":""...",D-1███ Se███r-7█████████B. ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
21,18977246,AURELIA,Blue Ethnic Motifs Maxi Dress,4.1,140,4299.0,59.0,"""₹1,750.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue ethnic motifs print max...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":13,""2_stars"":5,""3_stars"":12,""4_stars...","[{""percentage"":""77"",""value_name"":""Fit, Just Ri...",Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Vil███e B███a B█████████ata███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
22,18803110,Athena Girl,Yellow Floral Dress,3.5,6,2299.0,74.0,"""₹597.00""",INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Yellow floral print fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",no reviews,APE███PPA███S,"[{""size"":""10-11Y"",""value"":""2.25in"",""value_name...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
25,18956684,Forevermore,Mustard Yellow Chiffon Embroidred Ruffle Tiere...,4.2,5,1599.0,0.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Mustard yellow self design p...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",no reviews,Ami███nte███ise███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",10/███CHH███YA █████████ILL███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
26,18981160,Amydus,Blue & Orange Floral Wrap Dress,4.7,43,2799.0,0.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue and orange floral print...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BEG███01 ███EST██████,"[{""size"":""XXL"",""value"":""41.0in"",""value_name"":""...","357███has███, U█████████r, ███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
28,18207844,H&M,Women Blue Linen-blend Shirt Dress,3.0,7,1999.0,0.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/182...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Knee-length dress in soft jers...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""31.5in"",""value_name"":""B...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2
29,15736838,U&F,Black Solid Maxi Dress,3.8,1023,1999.0,66.0,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/157...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A casual fit with v-neckline, ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":140,""2_stars"":69,""3_stars"":124,""4_st...","[{""percentage"":""66"",""value_name"":""Fit, Just Ri...",SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","A-4███ect███7 N█████████ , █████████████████████1","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
31,15691054,QUIERO,Women Alluring Grey Polka Dots Trapeze Dress,3.4,7,2686.0,65.0,"""₹940.00""",INR,http://assets.myntassets.com/assets/images/156...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Get into fun mode every time y...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",no reviews,Per███nkl███esi██████,"[{""size"":""XS"",""value"":""9.25in"",""value_name"":""S...",B-1███1st███2nd█████████tor███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
33,13770986,all about you,Black Solid Midi Halter Neck Fit and Flare Dress,4.2,38,2999.0,0.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid fit & flare dres...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2
34,17586858,RARE,Women Orange Georgette A-Line Midi Dress,3.4,23,1799.0,55.0,"""₹809.00""",INR,http://assets.myntassets.com/assets/images/175...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Orange geometric print a-lin...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",EPI███RAN███PVT██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",EPI███RAN███PVT█████████ FI███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2
35,17692606,Style Quotient,Women Navy Blue Solid Cut-Out Detail Sheath Mi...,3.9,12,1899.0,53.0,"""₹892.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Navy blue solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2

## Step 11: Create Derived Column

In [36]:
df['final_price'] = df['final_price'].astype(str)

df['final_price'] = df['final_price'].str.replace('₹', '', regex=False)
df['final_price'] = df['final_price'].str.replace(',', '', regex=False)
df['final_price'] = df['final_price'].str.replace('"', '', regex=False)
df['final_price'] = df['final_price'].str.extract(r'(\d+\.?\d*)')[0]

df['final_price'] = pd.to_numeric(df['final_price'])

df['total_amount'] = df['final_price'] * df['quantity']

In [37]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,quantity,total_amount
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,2999.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Colourblocked A-Line dressV-ne...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...","604███TH ███OR,█████████ITA███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5998.0
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,2419.0,INR,http://assets.myntassets.com/assets/images/214...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid solid maxi dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4838.0
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,2094.0,INR,http://assets.myntassets.com/assets/images/212...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""embellished solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Kil███5/1███ 18█████████ 22███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4188.0
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,628.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black floral print a-line dr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",243███244███ Pa█████████rat█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1256.0
5,21664936,Label Ritu Kumar,Candy Striped Pure Cotton Maxi Dress,0.0,0,5900.0,30.0,4130.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Multicoloured striped fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,8260.0
6,21665324,Harpa,Sweetheart Neck Puff Sleeves Sheath Dress,2.3,4,1999.0,55.0,899.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid sheath dressSweetheart n...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,HAR███RET███ PV█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","45-███ FI███ FL█████████C,O███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1798.0
7,21664854,aarke Ritu Kumar,Cotton A-Line Dress,4.0,6,2200.0,30.0,1540.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Green chevron print a-line d...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3080.0
10,21980370,Tokyo Talkies,Mini A-Line Dress,3.7,26,1599.0,79.0,335.0,INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid A-line dressRound neckSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,670.0
11,21616436,Curves by MISH,Plus Size Shoulder Straps Embellished Maxi Dress,0.0,0,3999.0,37.0,2519.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid maxi dressShoulder strap...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",MIS███ESI███ LI██████,"[{""size"":""XL"",""value"":""40.0in"",""value_name"":""T...",GAL███O 4███ULA█████████IRE███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5038.0
12,21988674,Sangria,Floral Printed Tiered A-Line Dress,0.0,0,2999.0,80.0,599.0,INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue floral print a-line dre...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",D-2███Sec███ 06█████████uta███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1198.0
13,22004792,WoowZerz,Button Detailed Mini Blazer Dress,4.8,26,2495.0,50.0,1247.0,INR,http://assets.myntassets.com/assets/images/220...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid blazer dressLapel collar...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Man███ Fa███ona██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",B-8███2nd███oor█████████r I███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,2494.0
14,21979790,Vishudh,Floral Printed A-Line Midi Dress,3.8,55,2049.0,77.0,471.0,INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Turquoise blue floral print a-...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":3,""3_stars"":8,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Tight""}...",Fla███tar███mme██████,"[{""size"":""S"",""value"":""36.5in"",""value_name"":""Bu...","1st███oor███abi█████████02,███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,942.0
15,18962890,Athena,Fuchsia Solid Asymmetric Hem A-Line Maxi Dress,4.0,34,2499.0,64.0,899.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Fuchsia solid A-line dressShou...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1798.0
16,19027298,DressBerry,Girls Pink & Navy Blue Floral Printed Shirt Co...,3.8,40,1499.0,41.0,884.0,INR,http://assets.myntassets.com/assets/images/190...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink and navy blue floral pr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":6,""4_stars"":...",no reviews,Vis███ St███,"[{""size"":""12-13Y"",""value"":""28.0in"",""value_name...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1768.0
18,18951626,Berrylush,Women Green Solid Twist & Knot Dress,4.0,60,1899.0,78.0,398.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Look ravishing when you wear t...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""33.5in"",""value_name"":""Fr...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,796.0
19,18816460,Ethnovog,Women Navy Blue Velvet A-Line Made To Measure ...,3.7,6,7828.0,52.0,3757.0,INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy blue solid a-line dressSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Net███enu███ech█████████Pvt██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o.1███ari█████████oun███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,7514.0
20,18944812,DRAAX Fashions,Pink Chiffon Fit and Flare Dress,3.6,8,2399.0,0.0,2399.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink self design self design...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Dra███Fas███ns █████████vat████████████,"[{""size"":""XXS"",""value"":""32.0in"",""value_name"":""...",D-1███ Se███r-7█████████B. ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4798.0
21,18977246,AURELIA,Blue Ethnic Motifs Maxi Dress,4.1,140,4299.0,59.0,1750.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue ethnic motifs print max...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":13,""2_stars"":5,""3_stars"":12,""4_stars...","[{""percentage"":""77"",""value_name"":""Fit, Just Ri...",Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Vil███e B███a B█████████ata███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3500.0
22,18803110,Athena Girl,Yellow Floral Dress,3.5,6,2299.0,74.0,597.0,INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Yellow floral print fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",no reviews,APE███PPA███S,"[{""size"":""10-11Y"",""value"":""2.25in"",""value_name...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1194.0
25,18956684,Forevermore,Mustard Yellow Chiffon Embroidred Ruffle Tiere...,4.2,5,1599.0,0.0,1599.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Mustard yellow self design p...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",no reviews,Ami███nte███ise███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",10/███CHH███YA █████████ILL███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3198.0
26,18981160,Amydus,Blue & Orange Floral Wrap Dress,4.7,43,2799.0,0.0,2799.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue and orange floral print...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BEG███01 ███EST██████,"[{""size"":""XXL"",""value"":""41.0in"",""value_name"":""...","357███has███, U█████████r, ███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5598.0
28,18207844,H&M,Women Blue Linen-blend Shirt Dress,3.0,7,1999.0,0.0,1999.0,INR,http://assets.myntassets.com/assets/images/182...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Knee-length dress in soft jers...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""31.5in"",""value_name"":""B...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,3998.0
29,15736838,U&F,Black Solid Maxi Dress,3.8,1023,1999.0,66.0,679.0,INR,http://assets.myntassets.com/assets/images/157...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A casual fit with v-neckline, ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":140,""2_stars"":69,""3_stars"":124,""4_st...","[{""percentage"":""66"",""value_name"":""Fit, Just Ri...",SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","A-4███ect███7 N█████████ , █████████████████████1","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1358.0
31,15691054,QUIERO,Women Alluring Grey Polka Dots Trapeze Dress,3.4,7,2686.0,65.0,940.0,INR,http://assets.myntassets.com/assets/images/156...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Get into fun mode every time y...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",no reviews,Per███nkl███esi██████,"[{""size"":""XS"",""value"":""9.25in"",""value_name"":""S...",B-1███1st███2nd█████████tor███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1880.0
33,13770986,all about you,Black Solid Midi Halter Neck Fit and Flare Dress,4.2,38,2999.0,0.0,2999.0,INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid fit & flare dres...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,5998.0
34,17586858,RARE,Women Orange Georgette A-Line Midi Dress,3.4,23,1799.0,55.0,809.0,INR,http://assets.myntassets.com/assets/images/175...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Orange geometric print a-lin...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",EPI███RAN███PVT██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",EPI███RAN███PVT█████████ FI███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1618.0
35,17692606,Style Quotient,Women Navy Blue Solid Cut-Out Detail Sheath Mi...,3.9,12,1899.0,53.0,892.0,INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Navy blue solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1784.0

## Step 12: Save Cleaned Dataset

In [40]:
df.to_csv("Celebal_Assignment_1.csv",index=False)

In [41]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,best_offer,more_offers,category,quantity,total_amount
0,21664722,Curvy Clan,Colourblocked A-Line Cotton Maxi Dress,3.7,3,2999.0,0.0,2999.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Colourblocked A-Line dressV-ne...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RUB███S C███,"[{""size"":""XL"",""value"":""42.0in"",""value_name"":""B...","604███TH ███OR,█████████ITA███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5998.0
1,21426422,Trendyol,Black Maxi Dress,4.1,10,4399.0,45.0,2419.0,INR,http://assets.myntassets.com/assets/images/214...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid solid maxi dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4838.0
2,21238004,COVER STORY,Embellished Shoulder Straps Velvet Sheath Dress,4.8,24,3490.0,40.0,2094.0,INR,http://assets.myntassets.com/assets/images/212...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""embellished solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Cov███Sto███Clo█████████ite███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Kil███5/1███ 18█████████ 22███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4188.0
4,21673378,RACHNA,Floral Print Flared Sleeve Crepe A-Line Mini D...,3.0,4,1299.0,51.0,628.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black floral print a-line dr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",no reviews,RAC███ AR███RIN█████████TD.███,"[{""size"":""M"",""value"":""38.0in"",""value_name"":""Bu...",243███244███ Pa█████████rat█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1256.0
5,21664936,Label Ritu Kumar,Candy Striped Pure Cotton Maxi Dress,0.0,0,5900.0,30.0,4130.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Multicoloured striped fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,8260.0
6,21665324,Harpa,Sweetheart Neck Puff Sleeves Sheath Dress,2.3,4,1999.0,55.0,899.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid sheath dressSweetheart n...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,HAR███RET███ PV█████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...","45-███ FI███ FL█████████C,O███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1798.0
7,21664854,aarke Ritu Kumar,Cotton A-Line Dress,4.0,6,2200.0,30.0,1540.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Green chevron print a-line d...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",no reviews,REL███CE ███U K█████████ATE█████████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""B...",Rel███ce ███uku█████████Ltd███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3080.0
10,21980370,Tokyo Talkies,Mini A-Line Dress,3.7,26,1599.0,79.0,335.0,INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid A-line dressRound neckSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,670.0
11,21616436,Curves by MISH,Plus Size Shoulder Straps Embellished Maxi Dress,0.0,0,3999.0,37.0,2519.0,INR,http://assets.myntassets.com/assets/images/216...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""solid maxi dressShoulder strap...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",MIS███ESI███ LI██████,"[{""size"":""XL"",""value"":""40.0in"",""value_name"":""T...",GAL███O 4███ULA█████████IRE███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5038.0
12,21988674,Sangria,Floral Printed Tiered A-Line Dress,0.0,0,2999.0,80.0,599.0,INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue floral print a-line dre...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",D-2███Sec███ 06█████████uta███████████████████...,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1198.0
13,22004792,WoowZerz,Button Detailed Mini Blazer Dress,4.8,26,2495.0,50.0,1247.0,INR,http://assets.myntassets.com/assets/images/220...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Solid blazer dressLapel collar...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Man███ Fa███ona██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",B-8███2nd███oor█████████r I███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,2494.0
14,21979790,Vishudh,Floral Printed A-Line Midi Dress,3.8,55,2049.0,77.0,471.0,INR,http://assets.myntassets.com/assets/images/219...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Turquoise blue floral print a-...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":3,""3_stars"":8,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Tight""}...",Fla███tar███mme██████,"[{""size"":""S"",""value"":""36.5in"",""value_name"":""Bu...","1st███oor███abi█████████02,███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,942.0
15,18962890,Athena,Fuchsia Solid Asymmetric Hem A-Line Maxi Dress,4.0,34,2499.0,64.0,899.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Fuchsia solid A-line dressShou...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""XS"",""value"":""32.5in"",""value_name"":""B...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1798.0
16,19027298,DressBerry,Girls Pink & Navy Blue Floral Printed Shirt Co...,3.8,40,1499.0,41.0,884.0,INR,http://assets.myntassets.com/assets/images/190...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink and navy blue floral pr...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":6,""4_stars"":...",no reviews,Vis███ St███,"[{""size"":""12-13Y"",""value"":""28.0in"",""value_name...",3rd███oor███o. █████████Mai███████████████████...,"{""applicable_on"":""Orders above Rs. 1099 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1768.0
18,18951626,Berrylush,Women Green Solid Twist & Knot Dress,4.0,60,1899.0,78.0,398.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Look ravishing when you wear t...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":0,""3_stars"":7,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""33.5in"",""value_name"":""Fr...",Plo███o- ███ 1s█████████Sui███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,796.0
19,18816460,Ethnovog,Women Navy Blue Velvet A-Line Made To Measure ...,3.7,6,7828.0,52.0,3757.0,INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy blue solid a-line dressSh...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",no reviews,Net███enu███ech█████████Pvt██████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Plo███o.1███ari█████████oun███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,7514.0
20,18944812,DRAAX Fashions,Pink Chiffon Fit and Flare Dress,3.6,8,2399.0,0.0,2399.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Pink self design self design...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Dra███Fas███ns █████████vat████████████,"[{""size"":""XXS"",""value"":""32.0in"",""value_name"":""...",D-1███ Se███r-7█████████B. ███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,4798.0
21,18977246,AURELIA,Blue Ethnic Motifs Maxi Dress,4.1,140,4299.0,59.0,1750.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue ethnic motifs print max...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":13,""2_stars"":5,""3_stars"":12,""4_stars...","[{""percentage"":""77"",""value_name"":""Fit, Just Ri...",Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Vil███e B███a B█████████ata███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3500.0
22,18803110,Athena Girl,Yellow Floral Dress,3.5,6,2299.0,74.0,597.0,INR,http://assets.myntassets.com/assets/images/188...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Yellow floral print fit & fl...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",no reviews,APE███PPA███S,"[{""size"":""10-11Y"",""value"":""2.25in"",""value_name...","Plo███o. ███, P█████████2Se███████████████████...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1194.0
25,18956684,Forevermore,Mustard Yellow Chiffon Embroidred Ruffle Tiere...,4.2,5,1599.0,0.0,1599.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Mustard yellow self design p...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",no reviews,Ami███nte███ise███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",10/███CHH███YA █████████ILL███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,3198.0
26,18981160,Amydus,Blue & Orange Floral Wrap Dress,4.7,43,2799.0,0.0,2799.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Blue and orange floral print...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",BEG███01 ███EST██████,"[{""size"":""XXL"",""value"":""41.0in"",""value_name"":""...","357███has███, U█████████r, ███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,5598.0
28,18207844,H&M,Women Blue Linen-blend Shirt Dress,3.0,7,1999.0,0.0,1999.0,INR,http://assets.myntassets.com/assets/images/182...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Knee-length dress in soft jers...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""31.5in"",""value_name"":""B...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,3998.0
29,15736838,U&F,Black Solid Maxi Dress,3.8,1023,1999.0,66.0,679.0,INR,http://assets.myntassets.com/assets/images/157...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""A casual fit with v-neckline, ...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":140,""2_stars"":69,""3_stars"":124,""4_st...","[{""percentage"":""66"",""value_name"":""Fit, Just Ri...",SVP███XPO███ PR█████████ITE███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","A-4███ect███7 N█████████ , █████████████████████1","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1358.0
31,15691054,QUIERO,Women Alluring Grey Polka Dots Trapeze Dress,3.4,7,2686.0,65.0,940.0,INR,http://assets.myntassets.com/assets/images/156...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Get into fun mode every time y...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",no reviews,Per███nkl███esi██████,"[{""size"":""XS"",""value"":""9.25in"",""value_name"":""S...",B-1███1st███2nd█████████tor███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1880.0
33,13770986,all about you,Black Solid Midi Halter Neck Fit and Flare Dress,4.2,38,2999.0,0.0,2999.0,INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Black solid fit & flare dres...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",unknown,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",no info,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses,2,5998.0
34,17586858,RARE,Women Orange Georgette A-Line Midi Dress,3.4,23,1799.0,55.0,809.0,INR,http://assets.myntassets.com/assets/images/175...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Orange geometric print a-lin...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",EPI███RAN███PVT██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",EPI███RAN███PVT█████████ FI███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1618.0
35,17692606,Style Quotient,Women Navy Blue Solid Cut-Out Detail Sheath Mi...,3.9,12,1899.0,53.0,892.0,INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":"" Navy blue solid sheath dress...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",no reviews,Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","615███hur███ate█████████,5 ███████████████████...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses,2,1784.0

## Summary: This assignment provided practical experience in working with real-world data using Python and the Pandas library. The dataset was imported into a DataFrame and carefully explored to understand its structure, column details, and overall quality. Different data cleaning techniques were applied to improve the dataset, including handling missing values, removing duplicate records, and dropping unnecessary columns. Various operations such as filtering rows and selecting specific columns were also performed to make the data more meaningful and organized. To extend the analysis further, a new column called total_amount was created using product price and quantity values. After completing all preprocessing steps, the final cleaned dataset was exported as a new CSV file, making it ready for future analysis and use.